### ISSUE TITLE
1st Question: What is the reads number should I use?

### ISSUE THREAD

**Issue by hmyh1202** [LiuLabUB/SAPPER#1]
As we all know, variation calling need a suitble reads number and depth. What the number of the reads should I use ?

**Comment by taoliu** [comment]
Since SAPPER is dealing with ChIP-seq or ATAC-seq data, within the significant peak regions called by any peak caller, the coverage should be sufficient. If you only keep top ranked peaks, depending on the factor you are investigating, in a current ChIP-seq or ATAC-seq library, the read coverage will easily reach 30fold which is the minimum requirement for WGS. Of course, in general, the more reads the better.

**Comment by hmyh1202** [comment]
Thank you!
